import img_1kE6X8S from "../../../Image/SAPxSNM/Paintings/img_1kE6X8S.jpg"
import img_2Es4k8z from "../../../Image/SAPxSNM/Paintings/img_2Es4k8z.jpg"
import img_4KJ4W2q from "../../../Image/SAPxSNM/Paintings/img_4KJ4W2q.jpg"
import img_9kf1B0Y from "../../../Image/SAPxSNM/Paintings/img_9kf1B0Y.jpg"
import img_9cq1U2g from "../../../Image/SAPxSNM/Paintings/img_9cq1U2g.jpg"
import img_4Sl5R7h from "../../../Image/SAPxSNM/Paintings/img_4Sl5R7h.jpg"
import img_3ze3K5i from "../../../Image/SAPxSNM/Paintings/img_3ze3K5i.jpg"
import img_0eZ9n6p from "../../../Image/SAPxSNM/Paintings/img_0eZ9n6p.jpg"
import img_1KJ0R3B from "../../../Image/SAPxSNM/Paintings/img_1KJ0R3B.jpg"
import img_4oC0Z6p from "../../../Image/SAPxSNM/Paintings/img_4oC0Z6p.jpg"
import img_8HS6d9C from "../../../Image/SAPxSNM/Paintings/img_8HS6d9C.jpg"
import img_6AA0C9U from "../../../Image/SAPxSNM/Paintings/img_6AA0C9U.jpg"
import img_4uL2u3B from "../../../Image/SAPxSNM/Paintings/img_4uL2u3B.jpg"
import img_8Ew7T2M from "../../../Image/SAPxSNM/Paintings/img_8Ew7T2M.jpg"
import img_2rE1N0S from "../../../Image/SAPxSNM/Paintings/img_2rE1N0S.jpg"
import img_4eO6Z1u from "../../../Image/SAPxSNM/Paintings/img_4eO6Z1u.jpg"
import img_1IR2W6q from "../../../Image/SAPxSNM/Paintings/img_1IR2W6q.jpg"
import img_3Jz4e3W from "../../../Image/SAPxSNM/Paintings/img_3Jz4e3W.jpg"
import img_1IR2W6f from "../../../Image/SAPxSNM/Paintings/img_1IR2W6f.jpg"
import img_1IR2W6w from "../../../Image/SAPxSNM/Paintings/img_1IR2W6w.jpeg"

export const paintingData = [
    {
        title: "Where's the Ant?",
        id: "1kE6X8S",
        img: img_1kE6X8S,
        artist: "Evan Radithya Nio",
        kelastahun: "X5 - 2025",
        medium: "Oil Pastel, Kertas",
        desc: "Di antara makanan makanan manis, seekor semut kecil merayap diam, tersembunyi. Ia bersembunyi dalam lipatan bayangan, menunggu saat untuk mencuri apa yang dengan hati-hati telah kita buat. Ia makan seolah koruptor, mengambil hasil dari sesuatu yang sudah kita bangun. Sebuah pengingat bahwa ada semut di antara kita yang tak bisa diabaikan. Kadang, mereka harus diinjak.   ",
        price: "Rp 250.000",
        contact: "08119207775",
    },
    {
        title: "The Sleeping Red Panda",
        id: "2Es4k8z",
        img: img_2Es4k8z,
        artist: "Kaelyn Sutanto",
        kelastahun: "2024",
        medium: "Cat Akrilik, Kanvas",
        desc: "Menceritakan : seekor panda merah yang tertidur dengan tenang dan nyaman di antara rerumputan hijau, seolah ingin menunjukkan makna ketenangan dan kehangatan dengan beristirahat.",
        price: "Rp 450.000",
        contact: "082122257817",
    },
    {
        title: "Dear Future Me",
        id: "4KJ4W2q",
        img: img_4KJ4W2q,
        artist: "Christy Josephine Pribadi",
        kelastahun: "2025",
        medium: "Cat Akrilik, Kanvas",
        desc: "Lukisan berjudul “Dear Future Me” menggambarkan seorang wanita yang sedang menatap layar televisi, di mana ia melihat kembali sosok dirinya di masa kecil, bertahun-tahun yang lalu. Jika diperhatikan dengan seksama, tampak bahwa masa kecil wanita tersebut divisualisasikan dengan nuansa biru. Warna biru di sini melambangkan ketenangan, rasa damai, dan kesederhanaan—sebuah refleksi dari masa kanak-kanak yang penuh dengan permainan, eksplorasi, serta rasa ingin tahu yang polos dan bebas. Namun, ketika melihat dirinya yang telah dewasa, suasana di sekitarnya berubah menjadi dominasi warna kuning. Warna ini menjadi simbol pergeseran hidup yang sangat kontras, seakan menggambarkan perubahan 180 derajat dari masa kecilnya. Hal ini juga sejalan dengan konsep colour wheel, di mana biru dan kuning berada pada sisi yang saling berlawanan, sehingga menegaskan pertentangan antara kedua fase kehidupannya. Selain itu, karya ini juga terinspirasi dari sebuah tren di media sosial, di mana seseorang merekam dirinya pada satu momen, lalu memutar kembali rekaman itu setelah 20+ tahun atau lebih untuk membandingkan siapa dirinya dulu dan siapa dirinya sekarang. Melalui lukisan ini, penonton diajak merenungkan perjalanan waktu, pertumbuhan diri, serta perubahan yang terjadi di sepanjang hidup manusia. ",
        price: "Rp 200.000",
        contact: "08973778489",
    },
    {
        title: "Guardian of the Sapphire Tides",
        id: "9kf1B0Y",
        img: img_9kf1B0Y,
        artist: "Keiko Giovanni Kurniawan",
        kelastahun: "XI7 - 2025",
        medium: "Cat Akrilik & Benang, Mixed Media",
        desc: "Karya seni yang mempesona ini menggambarkan seekor ikan cupang mistis, berbalut kilauan safir dan mutiara, menjaga kedalaman samudra mistis yang tenang. Sirip-siripnya yang halus berputar-putar bagai ombak yang mempesona, sementara benang-benang bertekstur dan awan-awan lembut membangkitkan keajaiban laut purba, seolah-olah air itu sendiri bernapas di bawah pengawasannya.",
        price: "Rp 2.400.000,00",
        contact: "085890007615",
    },
    {
        title: "The Beauty of Growing",
        id: "9cq1U2g",
        img: img_9cq1U2g,
        artist: "Kaelyn Sutanto",
        kelastahun: "2025",
        medium: "Cat Akrilik, Kanvas",
        desc: "Lukisan ini menggambarkan perjalanan tumbuh kembang seorang perempuan melalui simbol kue ulang tahun dan bunga-bunga yang mekar seiring bertambahnya usia; pada bagian bawah tampak kue kecil dengan bay angan dirinya bersama orangtua yang masih erat mendampingi, lalu semakin ke atas kue bertambah besar dengan lilin-lilin yang melambangkan pertambahan umur, sementara bunga yang semula kecil berubah menjadi bunga anggun yang merepresentasikan kecantikan saat memasuki pubertas, hingga akhirnya pada puncaknya tampak sosok gadis yang berdiri sendiri dengan percaya diri, dikelilingi bunga-bunga indah, menandakan bahwa ia telah tumbuh menjadi individu yang mandiri meski tetap membawa jejak kasih sayang orangtuanya dalam perjalanan hidupnya.",
        price: "Rp500.000",
        contact: "082122257817",
    },
    {
        title: "The End of the Road: Under the Shades of Beautiful Flowers",
        id: "4Sl5R7h",
        img: img_4Sl5R7h,
        artist: "Megan Victoria Tan",
        kelastahun: "2024",
        medium: "Gouache",
        desc: "War is a tragedy that can transform the warmth of a loved one's embrace into the fragrance of wilted petals on a gravestone. The veteran's journey is one of solitary remembrance, a procession where those he walks past become a vibrant, blooming elegy. With tears a silent rain on his face, he clutches a single flower and a balloon, a fragile anchor to the memory of lives now buried under the shades of blossoms. He is the last witness, bearing the weight of a garden of souls who have found their final peace. ",
        price: "Rp 555.555,00",
        contact: "08121008215",
    },
    {
        title: "Birds of a Feather",
        id: "3ze3K5i",
        img: img_3ze3K5i,
        artist: "Christy Josephine Pribadi",
        kelastahun: "XI7 - 2025",
        medium: "Cat Akrilik, Kanvas",
        desc: "“Birds of a Feather” adalah lukisan yang menampilkan keindahan burung macaw, salah satu burung ikonik dari Amerika Selatan. Burung ini dikenal lewat bulu-bulunya yang cerah dan mencolok: biru yang membentang di punggung dan sayapnya, berpadu dengan kuning hangat di bagian dadanya. Keanggunan warna-warna tersebut seolah menjadi simbol keceriaan sekaligus kekuatan alam. Melalui karya ini, saya ingin menyampaikan apresiasi terhadap keberadaan burung macaw. Di balik pesonanya, burung ini telah menghadapi ancaman nyata di alam liar akibat perburuan serta hilangnya habitat. Meskipun kondisi mereka perlahan mulai membaik, kesadaran untuk terus menjaga dan melestarikan keberadaannya sangatlah penting. Lukisan ini bukan hanya sekadar representasi visual, melainkan juga pengingat bahwa burung macaw adalah ciptaan Tuhan yang indah. Sebagai manusia, kita memiliki tanggung jawab untuk merawat, melindungi, dan memastikan keindahan ini tetap hidup untuk generasi yang akan datang.",
        price: "Rp 300.000",
        contact: "08973778489",
    },
    {
        title: "Senja di Pelabuhan",
        id: "0eZ9n6p",
        img: img_0eZ9n6p,
        artist: "Rayna Miyesha Gunawan",
        kelastahun: "XII8 - 2024",
        medium: "Cat Air, Kertas",
        desc: "Lukisan ini menggambarkan kisah para nelayan yang baru saja berangkat melaut saat langit senja mulai mewarnai cakrawala. Mercusuar berdiri gagah di tepi tebing, seakan menjadi saksi bisu atas setiap perjalanan yang dimulai dari pelabuhan kecil ini, sementara camar-camar memberi tanda kehidupan yang setia menemani laut.",
        price: "Rp 1.100.000",
        contact: "081262309083",
    },
    {
        title: "Kenangan dan Waktu yang Membeku ",
        id: "1KJ0R3B",
        img: img_1KJ0R3B,
        artist: "Zoey Chen",
        kelastahun: "X3 - 2025",
        medium: "Pensil, Kertas",
        desc: "Gambar ini melambangkan perjalanan hidup yang tidak bisa diulang, hanya bisa dikenang melalui jejak waktu, cerita, dan sisa keindahan. Gambarnya merupakan still life yang menekankan pada simbol kenangan, waktu terhenti, dan kefanaan. Seperti seorang yang pernah meninggalkan jam, buku, dan bunga di atas meja, kini benda benda itu menjadi saksi bisu bahwa momen berhenti, cerita tertinggal, dan keindahan pun akhirnya berhenti (layu). ",
        price: "Rp 450.000",
        contact: "081388990722",
    },
    {
        title: "Morning Brunch",
        id: "3Jz4e3W",
        img: img_3Jz4e3W,
        artist: "Graciela Fiorenza Thiesman",
        kelastahun: "X4 - 2025",
        medium: "Cat Air & Cat Akrilik, Kertas A3",
        desc: "Sarapan pagi kroisan dengan segelas susu hangat. Ditambahi oleh stroberi segar yang ditutupi sauce pistashio. ",
        price: "Tidak Dijual",
        contact: "089504084744",
    },
    {
        title: "Letters We Never Sent",
        id: "4oC0Z6p",
        img: img_4oC0Z6p,
        artist: "Emily Adelia",
        kelastahun: "2025",
        medium: "Pensil Warna, Kertas",
        desc: "Surat dalam botol melambangkan bentuk komunikasi dan pesan di masa lalu, ketika seseorang menuliskan perasaan atau pesan rahasia lalu dibuang ke laut sebagai simbol pelepasan atau “moving on”. Di masa kini, pesan itu menggambarkan bahwa meski zaman berubah, pesan dan jejak yang ditinggalkan manusia akan terus abadi dan tidak benar-benar hilang.",
        price: "Tidak Dijual",
        contact: "08111095380",
    },
    {
        title: "Keluar",
        id: "8HS6d9C",
        img: img_8HS6d9C,
        artist: "Erika Olivia Chang",
        kelastahun: "XII7 - 2025",
        medium: "Cat Akrilik, Kanvas",
        desc: "Anak yang sedang memecahkan cangkang telur dianggap sebagai seorang yang berinisiatif untuk tumbuh dengan keluar dari zona nyamannya. Latar gelap menandakan keberanian anak untuk berinisiatif tumbuh walaupun tidak mengetahui masa depannya. Telur yang dipecahkan sang anak adalah representasi mengenai kehidupan sang anak yang terlindungi dan nyaman-suatu tempat dimana ia sudah terbiasa. Rumput yang bertumbuh dalam ruangan dapat diartikan sebagai pertumbuhan asing yang harus sang anak terima (dan sebuah dorongan untuk berani). Sang anak memahat menjadi sebuah analogi bahwa keputusan yang dibuat membutuhkan kekuatan dan tekad. Anak tersebut mengambil keputusan dan inisiatif untuk berani bertumbuh dan mengukir masa depannya.",
        price: "Tidak Dijual",
        contact: "08129300800",
    },
    {
        title: "Not a Raccoon",
        id: "6AA0C9U",
        img: img_6AA0C9U,
        artist: "Anna Monica Sahuburua",
        kelastahun: "XI9 - 2025",
        medium: "Cat Akrilik, Kanvas",
        desc: "Karya saya menggambarkan seekor cacomistle, hewan yang sering disalah sangka sebagai kucing, rakun, atau hewan lainnya. Sebenarnya Cacomistle adalah spesies yang belum banyak diketahui dan spesiesnya masih menjadi hal yang membingungkan sehingga sekarang. Melalui karya ini saya ingin membangkit rasa ingin tahu lebih lagi dalam diri masyarakat yang melihatnya agar tidak menerima suatu ide atau bayangan tentang sesuatu hanya dari penampilannya, melainkan mempelajarinya lebih dalam lagi dan usahakan memahaminya lebih dalam untuk mencari tahu apa hal tersebut.",
        price: "Tidak Dijual",
        contact: "08111501678",
    },
    {
        title: "Waves of Silence ",
        id: "4uL2u3B",
        img: img_4uL2u3B,
        artist: "Christy Josephine Pribadi",
        kelastahun: "2025",
        medium: "Foam, Kertas",
        desc: "Di balik repetisi bentuk yang teratur, karya ini menyimpan keheningan yang bergelombang. Warna-warna yang bergradasi dari gelap menuju terang merepresentasikan perjalanan emosi dari beratnya kesunyian hingga hadirnya ketenangan. Setiap lekuk menyerupai riak ombak yang tak bersuara, mengalir perlahan dan meninggalkan ruang bagi penonton untuk merasakan kedalaman tanpa kata. “Waves of Silence” adalah perenungan tentang bagaimana diam pun bisa berbicara, dan keindahan seringkali lahir dari keheningan.",
        price: "Rp 400.000",
        contact: "08973778489",
    },
    {
        title: "From Predator to Prey",
        id: "8Ew7T2M",
        img: img_8Ew7T2M,
        artist: "Dillon Jasper Gunawan",
        kelastahun: "XIIA8 - 2024",
        medium: "Cat Air, Kertas",
        desc: "Betapa anehnya dari seekor hewan predator yang besar berevolusi menjadi seekor hewan kecil yang posisinya berada di paling bawah di rantai makanan.",
        price: "Rp 500.000",
        contact: "081511189518",
    },
    {
        title: "Birunya Harapan",
        id: "2rE1N0S",
        img: img_2rE1N0S,
        artist: "Jovita Mayleen",
        kelastahun: "XI8 - 2025",
        medium: "Cat Akrilik & Stik Eskrim, Infraboard",
        desc: "Karya ini menunjukkan bahwa dari hal-hal sederhana bisa tercipta keindahan. Bentuk-bentuk biru yang tersusun menggambarkan semangat, harapan, dan kebersamaan. Warna biru memberi rasa tenang dan damai, seperti langit yang luas tanpa batas.",
        price: "Rp 1.000.000,00",
        contact: "081290084430",
    },
    {
        title: "Flight of Tranquility",
        id: "4eO6Z1u",
        img: img_4eO6Z1u,
        artist: "Phoebe Audrey",
        kelastahun: "2024",
        medium: "Cat Akrilik, Kanvas",
        desc: "Lukisan  ini  menggambarkan diri yang  berada di situasi tenang setelah berbagai turbulensi yang telah dihadapi. Warna yang kontras antara biru dan kuning menjadi warna utama dalam  lukisan ini dan memberi efek yang mencolok. Fokus utama dalam lukisan ini adalah wanita    di tengah yang dikelilingi oleh burung-burung yang melambangkan kebebasan dan ketenangan.",
        price: "Rp 500.000",
        contact: "081280478114",
    },
    {
        title: "Harmony in Blue",
        id: "1IR2W6q",
        img: img_1IR2W6q,
        artist: "Rachel Yap",
        kelastahun: "XI2 - 2025",
        medium: "Kertas A3, cat air",
        desc: "Ikan cupang biru yang dulu sederhana kini menjadi simbol seni, tetap bersinar di tengah arus zaman sebagai identitas yang tak tergantikan.",
        price: "Tidak Dijual",
        contact: "08111511877",
    },
    {
        title: "The Dead Composer",
        id: "1IR2W6w",
        img: img_1IR2W6w,
        artist: "Candice Andrea",
        kelastahun: "X2 - 2025",
        medium: "Kertas, Pensil",
        desc: "Karya berjudul The Dead Composer ini menggambarkan kematian melalui simbol-simbol seperti tengkorak, jam pasir, dan lilin yang padam. Kehadiran biola, kartu, dan mahkota melambangkan musik, permainan, serta kejayaan yang pada akhirnya akan hilang bersama waktu. Karya ini mengajak penonton merenungkan bahwa kejayaan dan karya indah sekalipun tak bisa melawan akhir kehidupan.",
        price: "Rp 229.900",
        contact: "085117140982",
    },
    {
        title: "Literasi: Cahaya Terakhir",
        id: "1IR2W6f",
        img: img_1IR2W6f,
        artist: "Nicole Tokyo Liongdra",
        kelastahun: "2025",
        medium: "Kertas, Krayon",
        desc: "Di antara buku, waktu, tinta, dan lilin yang menyala membisikkan pesan: hidup mungkin berakhir, tapi jejak literasi tetap menyala.",
        price: "Rp 199.000",
        contact: "085891060510",
    },
]