import img_1kE6X8S from "../../../Image/SAPxSNM/Paintings/1kE6X8S.jpg"
import img_2Es4k8z from "../../../Image/SAPxSNM/Paintings/2Es4k8z.jpeg"
import img_4KJ4W2q from "../../../Image/SAPxSNM/Paintings/4KJ4W2q.jpeg"
import img_9kf1B0Y from "../../../Image/SAPxSNM/Paintings/9kf1B0Y.jpg"
import img_9cq1U2g from "../../../Image/SAPxSNM/Paintings/9cq1U2g.jpeg"
import img_4Sl5R7h from "../../../Image/SAPxSNM/Paintings/4Sl5R7h.jpg"
import img_3ze3K5i from "../../../Image/SAPxSNM/Paintings/3ze3K5i.jpeg"
import img_0eZ9n6p from "../../../Image/SAPxSNM/Paintings/0eZ9n6p.jpeg"
import img_1KJ0R3B from "../../../Image/SAPxSNM/Paintings/1KJ0R3B.jpg"
import img_4oC0Z6p from "../../../Image/SAPxSNM/Paintings/4oC0Z6p.jpeg"
import img_8HS6d9C from "../../../Image/SAPxSNM/Paintings/8HS6d9C.jpg"
import img_6AA0C9U from "../../../Image/SAPxSNM/Paintings/6AA0C9U.jpeg"
import img_4uL2u3B from "../../../Image/SAPxSNM/Paintings/4uL2u3B.jpg"
import img_8Ew7T2M from "../../../Image/SAPxSNM/Paintings/8Ew7T2M.jpeg"
import img_2rE1N0S from "../../../Image/SAPxSNM/Paintings/2rE1N0S.jpeg"
import img_4eO6Z1u from "../../../Image/SAPxSNM/Paintings/4eO6Z1u.jpg"
import img_1IR2W6q from "../../../Image/SAPxSNM/Paintings/1IR2W6q.jpeg"
import img_9IH9g1W from "../../../Image/SAPxSNM/Paintings/9IH9g1W.jpg"
import img_8Yu8L1L from "../../../Image/SAPxSNM/Paintings/8Yu8L1L.jpeg"
import img_4Rz8c9J from "../../../Image/SAPxSNM/Paintings/4Rz8c9J.jpeg"
import img_3au1j0j from "../../../Image/SAPxSNM/Paintings/3au1j0j.jpg"
import img_7Ua2A7Y from "../../../Image/SAPxSNM/Paintings/7Ua2A7Y.jpeg"
import img_9JO5t4X from "../../../Image/SAPxSNM/Paintings/9JO5t4X.jpeg"
import img_9cC9Q8t from "../../../Image/SAPxSNM/Paintings/9cC9Q8t.jpg"
import img_6MF5d6g from "../../../Image/SAPxSNM/Paintings/6MF5d6g.jpeg"
import img_4LQ4v3d from "../../../Image/SAPxSNM/Paintings/4LQ4v3d.jpg"
import img_0kU9j4s from "../../../Image/SAPxSNM/Paintings/0kU9j4s.jpeg"
import img_4Rn5g2n from "../../../Image/SAPxSNM/Paintings/4Rn5g2n.jpg"
import img_1Us5V0u from "../../../Image/SAPxSNM/Paintings/1Us5V0u.jpg"
import img_0sM9v2V from "../../../Image/SAPxSNM/Paintings/0sM9v2V.jpeg"
import img_8Dg2d9n from "../../../Image/SAPxSNM/Paintings/8Dg2d9n.jpeg"
import img_7YN8q8b from "../../../Image/SAPxSNM/Paintings/7YN8q8b.jpg"
import img_3kW1m9f from "../../../Image/SAPxSNM/Paintings/3kW1m9f.jpg"
import img_6ab2A1H from "../../../Image/SAPxSNM/Paintings/6ab2A1H.jpeg"
import img_2bD3J0E from "../../../Image/SAPxSNM/Paintings/2bD3J0E.jpeg"
import img_6Pa2f1f from "../../../Image/SAPxSNM/Paintings/6Pa2f1f.jpg"
import img_7ox1o9m from "../../../Image/SAPxSNM/Paintings/7ox1o9m.jpeg"
import img_6tB9a9N from "../../../Image/SAPxSNM/Paintings/6tB9a9N.jpg"
import img_5Dh8o3p from "../../../Image/SAPxSNM/Paintings/5Dh8o3p.jpeg"
import img_3Co2C2m from "../../../Image/SAPxSNM/Paintings/3Co2C2m.jpeg"
import img_1CL2C3m from "../../../Image/SAPxSNM/Paintings/1CL2C3m.jpg"
import img_2Py7B5H from "../../../Image/SAPxSNM/Paintings/2Py7B5H.JPG"
import img_0nN0q1D from "../../../Image/SAPxSNM/Paintings/0nN0q1D.jpg"
import img_9hS7s5t from "../../../Image/SAPxSNM/Paintings/9hS7s5t.jpg"
import img_6Tt8U6b from "../../../Image/SAPxSNM/Paintings/6Tt8U6b.jpg"
import img_3zC8j3O from "../../../Image/SAPxSNM/Paintings/3zC8j3O.jpeg"
import img_4VN5D4G from "../../../Image/SAPxSNM/Paintings/4VN5D4G.jpg"
import img_1tS2g3q from "../../../Image/SAPxSNM/Paintings/1tS2g3q.jpg"
import img_3Jz4e3W from "../../../Image/SAPxSNM/Paintings/3Jz4e3W.jpg"
import img_5II2x0O from "../../../Image/SAPxSNM/Paintings/5II2x0O.jpeg"
import img_9Go6L8C from "../../../Image/SAPxSNM/Paintings/9Go6L8C.jpeg"

export const paintingData = [
    {
        title:"But I'm Still Smiling!",
        id:"1kE6X8S",
        img:img_1kE6X8S,
        artist:"Faeara Zefanya Sahelangi",
        kelastahun:"XIIA7 - 2023",
        medium:"Kanvas 30 x 40, cat akrlik",
        desc:"Giant, cold, grey hands rip and rip at her body. Her beautiful, beautiful soul pours out and it paints its colorful hues on the black and empty canvas that is the unforgiving world. She is torn and she is rotting, but the beam on her face never wavers — that's what they want to see. It's frozen, and she's still smiling. Tangan-tangan raksasa, dingin, dan abu-abu merobek tubuhnya. Jiwanya yang indah, begitu indah, mengalir keluar dan melukis warna-warna cerahnya sendiri di atas kanvas hitam yang kosong, yang adalah dunia tanpa ampun. Dia terkoyak dan membusuk, namun senyum di wajahnya tak pernah pudar — itulah yang mereka ingin lihat. Wajahnya membeku, dan dia masih tersenyum.",
        price:"Rp450.000",
        contact:"08111911500",
    },
{
        title:"Medusa: The Gaze of Tragedy and Power",
        id:"2Es4k8z",
        img:img_2Es4k8z,
        artist:"Natalia Khristina",
        kelastahun:"XIIA7 - 2024",
        medium:"canson A3, watercolor",
        desc:"Medusa dulunya wanita cantik, namun setelah diserang oleh Poseidon di kuil Athena, ia dikutuk oleh dewi Athena. Rambutnya berubah menjadi ular, dan tatapannya bisa mengubah siapa pun menjadi batu. Hidupnya penuh kesendirian dan ketakutan, dijauhi oleh dunia karena kutukan yang tidak dimintanya. Namun dibalik sosoknya yang menyeramkan medusa memiliki kesedihan tersendiri dalam hidupnya yang mendalam.",
        price:"Rp250.000",
        contact:"081386899822",
    },
{
        title:"Athena",
        id:"4KJ4W2q",
        img:img_4KJ4W2q,
        artist:"Joanne Edelina Hartanto",
        kelastahun:"XIIA2 - 2024",
        medium:"Kertas watercolor A3(29,7 x 42,0 cm), cat air",
        desc:"Athena adalah dewi kebijaksanaan, strategi perang, seni, dan keterampilan. Dewi Athena seringkali dideskripsikan sebagai seseorang yang bijak, percaya diri, bertekad, dan sering membantu. Di karya ini, saya melukiskan Athena sebagai sosok yang terlihat pintar dan baik hati. Di karya ini, saya juga menggambarkan senjata Athena yaitu sebuah tombak dan juga perisainya untuk menunjukan bahwa ia adalah sosok yang kuat dan berpengalaman dalam hal perperangan. Di atas perisai, terdapat burung hantu yang menjadi simbol kebijakan dan juga kepintaran yang terdapat pada sosok Athena. Sedangkan daun olive yang terdapat sebagai bingkai merupakan tanaman pemberian Athena terhadap kota Athens sebagai simbol perlindungan Athena dan perdamaian. Sedangkan bunga tiger lily seringkali digambarkan sebagai simbol kekuatan dan kepercayaan diri.",
        price:"Rp270.000",
        contact:"08118141007",
    },
{
        title:"In Serenity, She Weeps",
        id:"9kf1B0Y",
        img:img_9kf1B0Y,
        artist:"Faeara Zefanya Sahelangi",
        kelastahun:"XIIA7 - 2023",
        medium:"Kertas watercolor A3, cat watercolor",
        desc:"She stares longingly from the beachside into the unreachable horizon. Birds sing, flowers bloom, waves splash and looking around, this is the perfect home. But the peace quickly turns to deafening silence and she can only stare longingly as another one-sided love leaves her behind. Dia menatap dengan penuh kerinduan dari tepi pantai ke cakrawala yang tak terjangkau. Burung-burung bernyanyi, bunga-bunga bermekaran, ombak berdebur, dan melihat sekeliling, ini adalah pulau yang sempurna. Namun, kedamaian itu dengan cepat berubah menjadi keheningan yang memekakkan, dan dia hanya bisa menatap dengan penuh kerinduan saat cinta yang tak terbalas kembali meninggalkannya.",
        price:"Rp1.000.000",
        contact:"08111911500",
    },
{
        title:"quiet afternoon with lemon tea",
        id:"9cq1U2g",
        img:img_9cq1U2g,
        artist:"Keysia Aurelia Rawung",
        kelastahun:"X3 - 2024",
        medium:"kertas gambar 30x40cm, pensil",
        desc:"Ini adalah karya still life saya yang pertama, digambar ini saya merasakan sore yang nyaman, menenangkan, dan sunyi. saya juga merasakan aroma asam segar dari teh lemon yang telah diseduh. suasana yang hangat dipadukan dengan teh yang segar.",
        price:"Rp 100.000,00",
        contact:"082188603488",
    },
{
        title:"Chameleon in Her Comfort Zone",
        id:"4Sl5R7h",
        img:img_4Sl5R7h,
        artist:"Angela Tang ",
        kelastahun:"XI7 - 2024",
        medium:"Watercolor paper size A3, cat air",
        desc:"Karya ini menggambarkan seekor chameleon/bunglon yang berada di zona nyamannya saat ia lelah dimana ia sangat nyaman dengan tempatnya yaitu pada pohon dan warna hijau (warna biasa bunglon). Yang saya ingin sampaikan dari gambar ini adalah ketika kita capek dalam meraih sesuatu dll, tidak ada salahnya jika kita beristirahat dan mengisi ulang energi kita untuk sebentar. Jangan terlalu memaksakan diri terus-menerus tanpa memberi waktu untuk istirahat. Memberi diri kita waktu untuk beristirahat justru bisa membuat kita lebih produktif dan fokus ketika kita kembali berusaha.",
        price:"Rp250.000",
        contact:"08118787767",
    },
{
        title:"A Serene Morning ",
        id:"3ze3K5i",
        img:img_3ze3K5i,
        artist:"Kaylene Meredith Xie",
        kelastahun:"XIIA7 - 2024",
        medium:"kertas A3, pensil warna",
        desc:"Seorang wanita duduk santai di balkon rumahnya yang menghadap pemandangan laut yang tenang. Ditemani segelas teh dan croissant, ia menikmati pagi yang damai. Angin sepoi-sepoi dari laut menyapu rambutnya, sementara sinar matahari pagi yang hangat menyinari gaunnya yang berwarna ungu lembut. Dengan senyum yang tenang, wanita itu tampak tenggelam dalam pikirannya, merenungkan keindahan alam dan menikmati momen ketenangan di antara hiruk-pikuk kehidupan sehari-hari.",
        price:"Rp 800.000,-",
        contact:"085106299833",
    },
{
        title:"Corners of the Market",
        id:"0eZ9n6p",
        img:img_0eZ9n6p,
        artist:"Keira Alexandra Lim",
        kelastahun:"XIIA7 - 2024",
        medium:"kertas 30x42, watercolor",
        desc:" Lukisan cat air ini menangkap suasana ramai di sebuah pasar tradisional. . Latar belakang menampilkan gedung-gedung warga dengan jendela dan pintu pernuh warna. Suasana hiruk-pikuk pasar terasa damai dan romantis, mencerminkan kehidupan sehari-hari masyarakat lokal dengan kehangatan dan keceriaan.",
        price:"Rp 200.000",
        contact:"081910112007",
    },
{
        title:"Footsteps of a Hero",
        id:"1KJ0R3B",
        img:img_1KJ0R3B,
        artist:"Madeleine Fidelia Tjandra",
        kelastahun:"XIIA2 - 2024",
        medium:"Canson 29,5 x 41,5 cm, pensil warna, cat akrilik, cat air",
        desc:`Inspired by "honkai impact 3rd", this painting tells a story about a girl that want to become like her teacher and becoming the world's savior. Until one day, her teacher died sacrificing her life to protect the world. She then follow her footsteps and become the new world savior.`,
        price:"Rp800.000,00",
        contact:"0818872874",
    },
{
        title:"Zaman Dahulu",
        id:"3Jz4e3W",
        img:img_3Jz4e3W,
        artist:"Phoebe Lynelle Budiman ",
        kelastahun:"X6 - 2024",
        medium:"Kertas gambar a3, pensil",
        desc:"Salah satu potret sisi kehidupan di masa lalu.  Mengingat masa kecil oma saya (1966an). Dimana jaman dahulu kala orang-orang masih minum air dari teko/kendi.",
        price:"Tidak Dijual",
        contact:"081513377840",
    },
{
        title:"Heavenly Judgement",
        id:"4oC0Z6p",
        img:img_4oC0Z6p,
        artist:"Kaylene Meredith Xie",
        kelastahun:"XIIA7 - 2024",
        medium:"kertas A3, pensil warna",
        desc:"Themis adalah salah seorang Titan dalam mitologi Yunani. Themis memiliki arti Hukum Alam. Ia adalah tubuh dari aturan, hukum, dan adat. Themis ditunjukan dirinya memakai penutup kepala dan memegang pedang karena Ia melambangkan kesepakatan bersama, bukan dari paksaan luar.",
        price:"Rp 1.000.000,-",
        contact:"085106299833",
    },
{
        title:"Streetcar",
        id:"8HS6d9C",
        img:img_8HS6d9C,
        artist:"Catherine Kusuma Surya",
        kelastahun:"XIIA2 - 2024",
        medium:"Kertas gambar A3, campuran cat gouache dan charcoal",
        desc:"Streetcar' merupakan sebuah karya yang menggambarkan perasaan melalui lintasan waktu. Perkembangan menjadi seorang dewasa bukanlah hal yang mudah, dan karya inilah bertujuan untuk menyampaikan perasaan tersebut. Saya berharap karya ini tidak hanya menyentuh hati kaum muda saja, tetapi setiap orang yang merasa kesepian atau tidak yakin akan masa depan. ",
        price:"Rp 350.000",
        contact:"082299008598",
    },
{
        title:"Wings of Dedication",
        id:"6AA0C9U",
        img:img_6AA0C9U,
        artist:"Kaylene Meredith Xie",
        kelastahun:"XIIA7 - 2024",
        medium:"kertas A3, pensil warna",
        desc:"Seorang penari balet dengan sayap menggambarkan dedikasinya yang mendalam dalam mengeksplorasi peran hingga melampaui batas manusia biasa. Setiap gerakannya mencerminkan transformasi total, seakan benar-benar menjadi makhluk bersayap, penuh keanggunan dan ketelitian. Dalam ruang yang megah, ia menunjukkan bahwa kesempurnaan seni tercapai melalui pengorbanan, latihan, dan penyatuan tubuh serta jiwa dengan karakternya.",
        price:"Rp 800.000,-",
        contact:"085106299833",
    },
{
        title:"Whiskers in the Waters",
        id:"4uL2u3B",
        img:img_4uL2u3B,
        artist:"Catherine Nicole Yuen",
        kelastahun:"XI9 - 2024",
        medium:"Kertas watercolour 30 x 40cm, cat watercolour",
        desc:"Whilst finding inspiration I had stumbled upon a picture of an otter. It's bright eyes had almost brightened the murky waters around it, making the photograph all the more vivid and bright. As I painted each individual strand of fur, the realization of why I felt so strongly about painting this otter came to me. I had realized that my goal with this piece was simply to recreate the simple joy I felt when I first found this picture, with bright colors and even brighter eyes. ",
        price:"Tidak Dijual",
        contact:"08118905258",
    },
{
        title:"Mata Penjelajah Langit",
        id:"8Ew7T2M",
        img:img_8Ew7T2M,
        artist:"Axel Tara",
        kelastahun:"XIIA6 - 2024",
        medium:"Kertas A3, water color dan pensil warna",
        desc:"Di tengah langit biru yang cerah, sebuah balon udara berbentuk mata melayang tinggi, seolah-olah mengamati dunia di bawahnya. Mata ini melambangkan cara kita melihat dan memahami dunia di sekitar kita. Pemandangan di bawahnya, dengan laut dan pepohonan, mengingatkan kita betapa luasnya dunia yang bisa kita jelajahi jika kita mau melihat lebih jauh.",
        price:"Rp200.000",
        contact:"08118801502",
    },
{
        title:"Kehidupan yang Terus Mengalir",
        id:"2rE1N0S",
        img:img_2rE1N0S,
        artist:"Valeria Christy Abuku",
        kelastahun:"XIIA5 - 2023",
        medium:"35x45",
        desc:"Lukisan “Kehidupan yang Terus Mengalir” menggambarkan perjalanan hidup yang penuh dinamika. Arti dari lukisan ini mencakup proses beradaptasi dengan perubahan, menghadapi rintangan, dan menemukan kebahagiaan meskipun ada kesulitan. Aliran sungai yang tak terputus menunjukkan bahwa kehidupan selalu bergerak maju, mengajak kita untuk terus berjuang walaupun melewati kehidupan yang susah dan menghargai setiap momen.",
        price:"Rp700.000,00",
        contact:"08111249202",
    },
{
        title:"Reburn in the Mist of Darkness",
        id:"4eO6Z1u",
        img:img_4eO6Z1u,
        artist:"Madeleine Fidelia Tjandra",
        kelastahun:"XIIA2 - 2024",
        medium:"Kertas gambar 30 x 40 cm, cat air, pensil warna",
        desc:"Karya ini mengilustrasikan sebuah ruang gelap dengan lilin-lilin kecil yang menyala. Tetapi, seekor phoenix muncul dari salah satu lilin dan menjadi bara api di tengah kegelapan. Sama seperti phoenix, ambisi kita pun juga harus membakar lebih dahsyat daripada yang lainnya dan memberi kehangatan ditengah dunia yang gelap ini.",
        price:"Rp 1.500.000,00",
        contact:"0818872874",
    },
{
        title:"Stilasi Ubur Ubur",
        id:"1IR2W6q",
        img:img_1IR2W6q,
        artist:"Helen Jovanna",
        kelastahun:"XI8 - 2024",
        medium:"Kertas A3, cat air",
        desc:"Karya ini adalah lukisan stilasi yang berbentuk hewan ubur - ubur dengan pattern batik. Saya sanggat suka melihat biota laut ubur ubur menurut saya mereka sanggatlah unik dan indah. Saya juga sanggat suka dengan pattern batik, batik menurut saya merupakan kesenian tradisional indonesia yang sanggatlah indah untuk di nikmati mata. ",
        price:"Rp120.000",
        contact:"081212952285",
    },
{
        title:"Ebb and Flow of the Tiger",
        id:"9IH9g1W",
        img:img_9IH9g1W,
        artist:"Michiko Marchya",
        kelastahun:"XI9 - 2024",
        medium:"kertas A3 (29,7 x 42 cm), watercolor",
        desc:"Karya ini menampilkan seekor harimau yang tengah menyeruput air, dengan detail yang menggabungkan elemen alam dan garis-garis modern, di mana tubuh harimau dihiasi dengan motif tradisional mirip batik Mega Mendung serta unsur emas yang menonjol. Efek air yang bergelombang menambahkan dinamika dan aliran, menciptakan kesan bahwa harimau berada di antara alam nyata dan dunia fantasi. Melalui komposisi ini, tampak perpaduan kekuatan dan ketenangan alam, mencerminkan keteguhan serta ketenangan batin dari makhluk yang berkuasa.",
        price:"Rp 100.000,00",
        contact:"081990094800",
    },
{
        title:"Simfoni Sunyi",
        id:"8Yu8L1L",
        img:img_8Yu8L1L,
        artist:"Emily Adelia",
        kelastahun:"X6 - 2024",
        medium:"Kertas gambar A3, pensil 2B&HB",
        desc:"Karya ini menggambarkan keheningan. Keheningan yang hadir di antara benda yang ditemukan sehari-hari. Dengan permainan bayangan yang halus, karya ini menekankan pentingnya momen sederhana dalam kehidupan.",
        price:"Tidak Dijual",
        contact:"08111095380",
    },
{
        title:"Mimpi",
        id:"9Go6L8C",
        img:img_9Go6L8C,
        artist:"Tiffany Tee",
        kelastahun:"XIIA2 - 2024",
        medium:"Watercolor paper A3, cat airMimpi",
        desc:"Siapa bilang mimpi datang dengan sendirinya? Sosok gadis yang sedang menjahit merupakan simbol dari kerja keras dan dedikasi dalam meraih impian. Hal ini menunjukkan bahwa mimpi tidak dapat dicapai hanya dengan berleha-leha, melainkan melalui perjuangan, pengorbanan waktu, dan usaha yang konsisten.",
        price:"Rp300.000",
        contact:"081297359738",
    },
{
        title:"The Birth of Nyx",
        id:"4Rz8c9J",
        img:img_4Rz8c9J,
        artist:"Cherry Winata",
        kelastahun:"XIIA1 - 2024",
        medium:"Kertas ukuran A3 dengan infraboard. ",
        desc:"Bulan, bintang, terutama malam merupakan hal yang indah dan mistik yang disimbolkan sebagai dewi Nyx pada mitologi Yunani. Sehingga saya terinspirasi membuat sebuah karya yang melambangkan Nyx sebagai dewi yang berkilau ditengah gelapnya malam. Nyx yang digambarkan sebagai sesosok yang bersinar merupakan gambaran sebuah keindahan dan permulaan dari malam. ",
        price:"Rp 300.000",
        contact:"081514891850",
    },
{
        title:"Waiting...",
        id:"5II2x0O",
        img:img_5II2x0O,
        artist:"Tiffany Tee",
        kelastahun:"XIIA2 - 2024",
        medium:"Watercolor paper A3, cat air",
        desc:"Dewi Demeter, penguasa kesuburan dan pertanian yang sedang terbenam dalam kesedihan karena putrinya, Persephone diculik oleh Hades. Dengan penuh harapan, Demeter menantikan kepulangan sang buah hati, disertai dengan peralihan musim semi yang indah.",
        price:"Rp750.000",
        contact:"081297359738",
    },
{
        title:"Harmony",
        id:"3au1j0j",
        img:img_3au1j0j,
        artist:"Tiffany Tee",
        kelastahun:"XIIA2 - 2024",
        medium:"Watercolor paper A3, cat air",
        desc:"Lukisan ini menggambarkan interaksi antara landak dan bebek, simbol dari perbedaan yang saling melengkapi. Landak, dengan duri tajamnya berusaha beradaptasi dan membuka diri, sedangkan bebek mewakili kehangatan dan penerimaan. Karya ini mengingatkan kita bahwa, dalam kehidupan sehari-hari, sangat penting untuk belajar beradaptasi dan saling menerima agar kita dapat hidup harmonis di tengah masyarakat yang beragam.",
        price:"Rp500.000",
        contact:"081297359738",
    },
{
        title:"Tale from Above ",
        id:"7Ua2A7Y",
        img:img_7Ua2A7Y,
        artist:"Naru Widjaja",
        kelastahun:"XI8 - 2024",
        medium:"watercolor paper A3, watercolor ",
        desc:`"Tale from Above" depicts two giraffes of different heights, with the taller one seems to be enjoying the view above while the shorter one munched on the leaves it just harvested. Their distinct coat patterns—playful spots on the taller giraffe and softer lines on the shorter—highlight their uniqueness. The taller giraffe exudes a sense of freedom, while the shorter one embodies curiosity, and grumpiness, showcasing how their heights influence their experiences in the savanna.`,
        price:"Tidak Dijual",
        contact:"08118848191",
    },
{
        title:"The Innocent Spacegoat",
        id:"9JO5t4X",
        img:img_9JO5t4X,
        artist:"Darlene Felicia Sutyo",
        kelastahun:"XIIS2 - 2024",
        medium:"30 x 40 cm, cat akrilik",
        desc:"The Innocent Spacegoat bercerita tentang seorang anak yang masih lugu dan polos, sehingga ia tidak tahu bahwa ia sedang dijadikan “kambing hitam“ oleh orang-orang terdekatnya yang hanya memanfaatkan kebaikan nya. Ketika suatu masalah datang, anak tersebut selalu menjadi orang yang disalahkan, tidak bisa melawan dan hanya bisa menerima kenyataan bahwa ia hanyalah anak yang lemah dan gampang dimanfaatkan. Akan tetapi dibalik semua itu, ada sedikit cahaya harapan dari benak anak tersebut, harapan untuk kehidupan yang lebih baik. ",
        price:"Rp800.000",
        contact:"081288883249",
    },
{
        title:"Le Cygne",
        id:"9cC9Q8t",
        img:img_9cC9Q8t,
        artist:"Phoebe Audrey Saputra",
        kelastahun:"XIIS2 - 2024",
        medium:"Acrylic on A3 paper (29,7 x 42 cm)",
        desc:`Inspired by the "Swan Lake" ballet, this piece shows how obsession, grief, and loneliness can affect an artist. This solo shows Odette, dancing her "magnum opus" right before her untimely death. It begs the question of what an artist is without their obsession.`,
        price:"Rp2.230.000,00",
        contact:"081280478114",
    },
{
        title:"Unlikely Allies",
        id:"4VN5D4G",
        img:img_4VN5D4G,
        artist:"Krislyn Winny Riyadi",
        kelastahun:"XIIA6 - 2024",
        medium:"Kertas Canson 30 x 40 cm, cat air",
        desc:"Nick dan Judy, dua sosok yang berbeda namun saling melengkapi, telah melewati berbagai rintangan bersama. Awalnya, mereka hanyalah sekutu karena keadaan, namun persahabatan mereka tumbuh kuat seiring waktu. Setiap tantangan yang dihadapi semakin memperkuat ikatan mereka, membuktikan bahwa kerja sama dan kepercayaan adalah kunci dalam menghadapi dunia yang penuh dengan kejutan.",
        price:"Rp300.000",
        contact:"08989643192",
    },
{
        title:"Istimewa Kakatua",
        id:"1tS2g3q",
        img:img_1tS2g3q,
        artist:"Christian Rafael Adhimulia",
        kelastahun:"XI1 - 2024",
        medium:"Buku gambar A3, cat air, pensil, pulpen",
        desc:"Kakatua, dengan bulunya yang cerah dan eksotis, sering dihubungkan dengan keindahan alam dan harmoni dalam keberagaman. Lukisan ini dapat mencerminkan pentingnya menghargai perbedaan dan menikmati keunikan yang ada di sekitar kita. Dalam budaya tertentu, burung yang berwarna-warni dianggap sebagai pembawa pesan atau lambang harapan dan kebahagiaan.",
        price:"Rp 200.000 ",
        contact:"082189136599",
    },
{
        title:"Selene: The Goddess of the Moon",
        id:"6MF5d6g",
        img:img_6MF5d6g,
        artist:"Darlene Felicia Sutyo",
        kelastahun:"XIIS2 - 2024",
        medium:"Kertas A3, watercolour",
        desc:"Selene adalah dewi bulan dalam mitologi Yunani yang merupakan anak dari Tutan Hyperon dan Theia. Ia yang mempunyai kemampuan untuk menarik bulan melintasi langit dengan kudanya untuk memberikan cahay terang di langit yang gelap. Ia juga dapat  membuat manusia tertidur dan mengunjungi mimpi manusia tersebut untuk memberikan jawaban atas pertanyaan yang mungkin sedang mereka tanyakan. ",
        price:"Rp2.500.000",
        contact:"081288883249",
    },
{
        title:"Gajah",
        id:"4LQ4v3d",
        img:img_4LQ4v3d,
        artist:"Phoebe Audrey Saputra",
        kelastahun:"XIIS2 - 2023",
        medium:"Watercolor on A3 paper (29,7 x 42 cm)",
        desc:"Lukisan sebuah gajah.",
        price:"Rp700.000,00",
        contact:"081280478114",
    },
{
        title:"Curated Chaos",
        id:"0kU9j4s",
        img:img_0kU9j4s,
        artist:"Jeanice Sanricz Atmapralieto ",
        kelastahun:"XI7 - 2024",
        medium:"Kertas 29.5 X 41.5 cm, cat watercolour & poster colour",
        desc:`"Transforming disarray into art." Karya ini menggambarkan rusa, rusa terbuat dari sampah dan bahan bekas. Karya ini menunjukkan bahwa bahkan hal-hal yang biasanya kita sebut sampah, dapat diubah menjadi sebuah gambaran yang indah, ataupun sebuah karya seni.`,
        price:"Rp250.000",
        contact:"0813-1818-7933",
    },
{
        title:"Time Eats All His Children In The End",
        id:"4Rn5g2n",
        img:img_4Rn5g2n,
        artist:"Faeara Zefanya Sahelangi",
        kelastahun:"XIIA7 - 2024",
        medium:"Kertas watercolor A3, cat watercolor",
        desc:"Reaching out, the hand of cold bone touches and transforms the hand of warm flesh in its final moments. Bubbles surround them and a black hole awaits beneath them, swirling with colour. They represent a single promise: we all become creatures of death in the end. Mengulurkan tangan, tulang dingin menyentuh dan mengubah tangan dari daging hangat di saat-saat terakhirnya. Gelembung-gelembung mengelilingi dan sebuah lubang hitam menanti di bawah mereka, berputar dengan warna-warna. Mereka mewakili satu janji: kita semua akan menjadi makhluk kematian pada akhirnya.",
        price:"Rp350.000",
        contact:"08111911500",
    },
{
        title:"Whale Above the Waves",
        id:"1Us5V0u",
        img:img_1Us5V0u,
        artist:"Christabel Kinori",
        kelastahun:"XI1 - 2024",
        medium:"Kertas A3, Cat air",
        desc:"Karya ini melukiskan seekor paus yang meluncur dari atas ombak laut pada sore hari.  Terinspirasi dari paus yang pergi ke permukaan air untuk mengambil udara.",
        price:"Tidak Dijual",
        contact:"0857 7502 6665",
    },
{
        title:"The Male Peacock",
        id:"0sM9v2V",
        img:img_0sM9v2V,
        artist:"Joycelin Janani",
        kelastahun:"XI1 - 2024",
        medium:"kertas A3",
        desc:"In a forest, there lived a very beautiful peacock. His feathers are colorful, emitting gold, green and blue sparkles that amaze every creature that sees him, including attracting the attention of females that he likes. Every morning, when the sun begins to rise, the peacock will open its tail and dance in the sunlight, showing off its beauty to the world.",
        price:"Tidak Dijual",
        contact:"08119568818",
    },
{
        title:"Freshness in Every Sip",
        id:"8Dg2d9n",
        img:img_8Dg2d9n,
        artist:"Kaylee Ariella Simon",
        kelastahun:"X3 - 2024",
        medium:"kertas 30 x 42 cm, pensil 2b, pensil 4b, pensil 6b",
        desc:"Di dalam gambar ini, teko dan cangkir melambangkan sebuah kesederhanaan karena kedua barang terbuat dari tanah liat. Teko digunakan untuk membuat teh dan lemon memberikan tambahan kesegaran yang tiada tara. Teh di tuang ke dalam cangkir untuk dinikmati setiap tegukannya dalam kebersamaan. Gambar ini menunjukkan bahwa adanya keindahan dan kebersamaan dalam kesederhanaan yang akan membuat momen-momen kecil di dalam hidup kita berharga.",
        price:"Rp150.000",
        contact:"08170917806",
    },
{
        title:"A Dream of London: A City I Long to Visit",
        id:"7YN8q8b",
        img:img_7YN8q8b,
        artist:"Callista Kayleigh Supriyadi ",
        kelastahun:"XIIA8 - 2024",
        medium:"watercolour paper A3 (29.7 x 42 cm), cat air",
        desc:"Sebuah lukisan mengenai kota yang sangat indah dan terkenal akan budaya serta pemandangannya. It's London. Kota yang sangat ingin saya jumpai namun belum bisa terwujudkan. It really is a city that i long to visit.",
        price:"Rp500.000",
        contact:"0811402000",
    },
{
        title:"Swan Serenade in a Dreamy Oasis",
        id:"3kW1m9f",
        img:img_3kW1m9f,
        artist:"Jessica Feivel Lim",
        kelastahun:"XIIA2 - 2024",
        medium:"kanvas 30 x 40, cat akrilik",
        desc:`"Swan Serenade in a Dreamy Oasis" adalah lukisan yang menggambarkan angsa anggun yang meluncur di atas danau terpenuhi bunga teratai. Dengan cahaya lembut yang menyinari pemandangan, lukisan ini menciptakan suasana damai. Bunga teratai berwarna tampak seolah menari bersama angsa di permukaan air, menambah keindahan alam yang tenang ini.`,
        price:"Rp500.000",
        contact:"085161173676",
    },
{
        title:"Alternate Me",
        id:"6ab2A1H",
        img:img_6ab2A1H,
        artist:"Megan Victoria Tan",
        kelastahun:"XI9 - 2023-2024",
        medium:"Kertas aquarel A3 (29,7 x 42 cm), pensil warna",
        desc:`"In the dull and monotonous world where hope shrivels and despair blossoms, I wish to be a rainbow in your cloud..." This artwork features a portrait of black and white hue, combined with vibrant colors. In a universe where colors are forbidden, the character is reflecting on her last bit of her liveliest moments before her colors are bleached by the dreary and monochromatic reality of hustle and bustle. `,
        price:"Rp500.000",
        contact:"08121008215",
    },
{
        title:"The Beautiful Peacock",
        id:"2bD3J0E",
        img:img_2bD3J0E,
        artist:"Jessica Tandianto",
        kelastahun:"XI9 - 2024",
        medium:"29.7 x 42 cm, cat air",
        desc:"Seekor burung merak ini berbeda dari burung merak lainnya. Merak ini adalah merak biru yang dikenal kecantikan bulunya. Merak ini memiliki warna yang lebih cerah dan pola yang cukup sempurna. ",
        price:"Rp100.000",
        contact:"087876102689",
    },
{
        title:`Another Version of "Beauty and The Beast"`,
        id:"6Pa2f1f",
        img:img_6Pa2f1f,
        artist:"Elbellenaia Chrysilla",
        kelastahun:"XIIA7 - 2023-2024",
        medium:"Kertas  A3, Cat air dan pensil warna",
        desc:`Kisah ini terinspirasi dari kisah classic bernama "Beauty and the Beast" dimana Sang Perempuan Cantik di lukisan jatuh cinta pada Si Buruk Rupa. Kisah ini saya ubah sedikit dengan menambahkan elemen makhluk mitologi yang sebagian orang percaya akan keberadaannya.`,
        price:"Rp 600.000,00",
        contact:"0878 8882 8211",
    },
{
        title:"The Portal of Emotion",
        id:"7ox1o9m",
        img:img_7ox1o9m,
        artist:"Darlene Felicia Sutyo",
        kelastahun:"XIIS2 - 2024",
        medium:"Kertas A3, gouache",
        desc:"Karya ini terinspirasi dari film inside out 2, bercerita tentang seorang anak yang mulai beranjak remaja. Masa remaja ini digambarkan sebagai sebuah portal kaca dengan berbagai emosi yang mulai dialami remaja, yang didominasi oleh kecemasan, dan emosi lain nya seperti emosi cemas,iri, bosan, dan malu. Emosi ini saling berpantulan, dan emosi kebahagiaan yang mulai perlahan tertutupi oleh kecemasan.",
        price:"Rp1.000.000",
        contact:"081288883249",
    },
{
        title:"The Rhythm of Our Forever ",
        id:"6tB9a9N",
        img:img_6tB9a9N,
        artist:"Catherine Nicole Yuen",
        kelastahun:"XI9 - 2024",
        medium:"Kertas HVS 30 x 40cm, pen ",
        desc:"I had found a photograph from the 90s a while ago. It was of an older couple dancing in what seemed to be an old wedding dress and suit. They had both seemed so comfortable, so used to their steps and their dance that it made me think that this couldn't have been the first time they had danced together. I wanted to capture that nostalgia and show the comfort that these people have with each other through this piece. ",
        price:"Tidak Dijual",
        contact:"08118905258",
    },
{
        title:"Badak Psikedelik",
        id:"5Dh8o3p",
        img:img_5Dh8o3p,
        artist:"Darrell Jayden Adiwijaya",
        kelastahun:"XI6 - 2024",
        medium:"30 x 40cm, pensil warna",
        desc:"Dalam dunia yang penuh warna, seekor badak memilih untuk menampilkan diri dengan balutan warna-warni cerah yang mencerminkan rohnya yang berani. Setiap pola dan garis yang menghiasi tubuhnya adalah simbol dari perjalanan hidupnya yang penuh tantangan dan kegembiraan. Lukisan ini mengajak kita untuk merayakan keberanian dalam menampilkan keunikan diri dan keindahan dalam keberagaman.",
        price:"Tidak Dijual",
        contact:"HP: 081381462734 WA:‪ 081212567583‬",
    },
{
        title:"Pulang ke Hangatnya Senja",
        id:"3Co2C2m",
        img:img_3Co2C2m,
        artist:"Kenisha Wirananda",
        kelastahun:"XIIA4 - 2024",
        medium:"kertas 29,7 x 42 cm, krayon dan pensil warna",
        desc:"Karya ini mengisahkan kehidupan di desa tropis yang berada dalam kesederhanaan dan keharmonisan dengan alam. Jalan setapak yang terdapat di tengah gambar diterangi sinar matahari sore dan dikelilingi pohon-pohon tinggi yang kemudian menuntun kita ke suasana hangat dan tenang dari lingkungan kehidupan yang sederhana. Makna dari karya ini menawarkan pelarian dari keramaian kehidupan modern, dan kembali menghargai momen kehidupan yang dekat dengan alam.",
        price:"Rp300.000,00",
        contact:"087856795030",
    },
{
        title:"Kebahagiaan yang Begitu Sederhana",
        id:"1CL2C3m",
        img:img_1CL2C3m,
        artist:"Faye Tecira Xavier",
        kelastahun:"XI7 - 2024",
        medium:"Kertas A3 29,7 cm x 42 cm, cat air",
        desc:"Tahukah kalian bahwa berang-berang adalah salah satu spesies hewan yang paling setia dan senang bersosialisasi? Ya, begitulah kenyataannya, kendati demikian karya ini ingin mengangkat sisi lainnya yakni berupa pribadi berang-berang yang berdiri di lapisan es dan sedang akan memakan ikan; latar belakang berwarna biru identik dengan habitat berang-berang yang tinggal di air. Karya ini terinspirasi dari sosok berang-berang yang saya anggap sangat menggemaskan dan ternyata menyimpan berbagai sifat-sifat unik. Secara tidak langsung, karya ini ingin menyampaikan bahwa seringkali kebahagiaan dapat kita peroleh dari hal yang sederhana, seperti berang-berang yang tampak begitu bahagia hanya karena seekor ikan di tangannya.",
        price:"Rp100.000",
        contact:"082119064796",
    },
    {
        title: "From Predator to Prey",
        id: "2Py7B5H",
        img: img_2Py7B5H,
        artist: "Dillon Jasper Gunawan",
        kelastahun: "XIIA8 - 2024",
        medium: "kertas 30 x 42 cm, cat air",
        desc: "Sains membuktikan bahwa nenek moyang burung adalah dinosaurus. Salah satu contoh adalah struktur tulang ayam memiliki banyak kemiripan dengan struktur tulang T-rex. Sungguh mengejutkan bahwa terjadi perubahan dari predator yang besar dan kuat menjadi mangsa yang kecil dan lemah. T rex seekor predator menjadi ayam yang menjadi mangsa bagi burung lain yang juga keturunan dinosaurus. ",
        price: "Rp 750.000",
    },
    {
        title:"Zenosyne",
        id: "6Tt8U6b",
        img:img_6Tt8U6b,
        artist:"Catherine Nicole Yuen",
        kelastahun:"XI9 - 2024",
        medium:"Kertas watercolour 30 x 40cm, cat watercolour",
        desc:`"Zenosyne", meaning that time appears to be moving faster and faster, speeding towards an inevitable conclusion that will arrive unexpectedly soon. The owls remind me of that. It's eyes which distort the life around it, heralds of death that promise something ominous. I wanted to portray that feeling of something that's not quite organic, not quite alive. `,
        price:"Tidak Dijual",
        contact:"08118905258",
    },
{
        title:"More Beautiful in Dreams",
        id:"3zC8j3O",
        img:img_3zC8j3O,
        artist:"Aurelia Saroslie",
        kelastahun:"XIIS1 - 2023",
        medium:"kanvas 30x40 cm, cat akrilik",
        desc:"Menjelaskan mengenai indahnya mimpi dibanding realita. Banyaknya realita yang tidak sesuai dengan ekspektasi membuat mimpi menjadi tempat nyaman untuk pulang.",
        price:"Rp50.000",
        contact:"085770309510",
    },
]